name: BobTheBuilder
options:
  bundleIdPrefix: com.bobthebuilder
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "13.2"
  xcodeGenCompatibleVersion: "13.2"

schemes:
  BobTheBuilder-Dev:
    build:
      targets:
        BobTheBuilder: all
    run:
      config: Debug-Dev
    test:
      config: Debug-Dev
      targets:
        - name: BobTheBuilderTests
        - name: BobTheBuilderUITests
    profile:
      config: Release-Dev
    analyze:
      config: Debug-Dev
    archive:
      config: Release-Dev
  BobTheBuilder-Stage:
    build:
      targets:
        BobTheBuilder: all
    run:
      config: Debug-Stage
    test:
      config: Debug-Stage
      targets:
        - name: BobTheBuilderTests
        - name: BobTheBuilderUITests
    profile:
      config: Release-Stage
    analyze:
      config: Debug-Stage
    archive:
      config: Release-Stage
  BobTheBuilder-Prod:
    build:
      targets:
        BobTheBuilder: all
    run:
      config: Debug-Prod
    test:
      config: Debug-Prod
      targets:
        - name: BobTheBuilderTests
        - name: BobTheBuilderUITests
    profile:
      config: Release-Prod
    analyze:
      config: Debug-Prod
    archive:
      config: Release-Prod

settings:
  base:
    SWIFT_VERSION: "5.5"
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1,2"

configFiles:
  Debug-Dev: BobTheBuilder/Config/Development.xcconfig
  Debug-Stage: BobTheBuilder/Config/Staging.xcconfig
  Debug-Prod: BobTheBuilder/Config/Production.xcconfig
  Release-Dev: BobTheBuilder/Config/Development.xcconfig
  Release-Stage: BobTheBuilder/Config/Staging.xcconfig
  Release-Prod: BobTheBuilder/Config/Production.xcconfig

configs:
  Debug-Dev: debug
  Debug-Stage: debug
  Debug-Prod: debug
  Release-Dev: release
  Release-Stage: release
  Release-Prod: release

targets:
  BobTheBuilder:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: BobTheBuilder
        excludes:
          - "Config/*.xcconfig"
    info:
      path: BobTheBuilder/App/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: "Bob the Builder"
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        ITSAppUsesNonExemptEncryption: false
        UILaunchScreen: {}
        UIRequiresFullScreen: false
        UIApplicationSupportsIndirectInputEvents: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "We need access to your camera to capture project photos."
        NSPhotoLibraryUsageDescription: "We need access to your photo library to save and select project photos."
        NSLocationWhenInUseUsageDescription: "We need your location to track project sites and field work."
        API_BASE_URL: $(API_BASE_URL)
        ENVIRONMENT: $(ENVIRONMENT)
    settings:
      base:
        PRODUCT_NAME: $(APP_NAME)
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_ID)
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: "5.5"
        INFOPLIST_FILE: BobTheBuilder/App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICON)
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
    entitlements:
      path: BobTheBuilder/BobTheBuilder.entitlements
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        runOnlyWhenInstalling: false

  BobTheBuilderTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - BobTheBuilderTests
    dependencies:
      - target: BobTheBuilder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bobthebuilder.app.tests
        SWIFT_VERSION: "5.5"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"

  BobTheBuilderUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - BobTheBuilderUITests
    dependencies:
      - target: BobTheBuilder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bobthebuilder.app.uitests
        SWIFT_VERSION: "5.5"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
